const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let data={},state={template:"classic",bg:"#fffdf9",filter:"Original",border:18,radius:6,shadow:16,fit:"fill",images:[],image:null,posX:0,posY:0,zoom:100,text:null,textBold:false,textItalic:false,textSize:34,letterSpacing:1,decor:[],collage:false},history=[],future=[],gallery=JSON.parse(localStorage.getItem("framey-gallery")||"[]");
fetch("data.json").then(r=>r.json()).then(d=>{data=d;init()});
function init(){buildFrameChoices();buildFilterChoices();buildBgChoices();buildStickerChoices();buildCategories();renderTemplateGrid();bind();draw();if(localStorage.getItem("framey-dark")==="true")document.body.classList.add("dark")}
function bind(){
$$("[data-page]").forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$("nav button").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("framey-dark",document.body.classList.contains("dark"))};
$("#helpBtn").onclick=()=>$("#helpModal").classList.add("show");$$(".modal-close").forEach(b=>b.onclick=()=>b.closest(".modal").classList.remove("show"));
$("#photoInput").onchange=e=>[...e.target.files].forEach(loadImage);
["border","radius","shadow","posX","posY","zoom","textSize","letterSpacing"].forEach(id=>$("#"+id).oninput=()=>{push();state[id]=+$("#"+id).value;draw()});
$("#bgColor").oninput=e=>{push();state.bg=e.target.value;draw()};$("#fitBtn").onclick=()=>{push();state.fit="fit";draw()};$("#fillBtn").onclick=()=>{push();state.fit="fill";draw()};
$("#removePhoto").onclick=()=>{if(state.images.length){push();state.images.pop();state.image=state.images.at(-1)||null;draw();toast("Photo removed")}};
$("#addText").onclick=()=>{push();state.text=state.text||"little moments";$("#textEditor").classList.remove("hidden");$("#textValue").value=state.text;draw()};
$("#textValue").oninput=e=>{state.text=e.target.value;draw()};$("#boldBtn").onclick=()=>{push();state.textBold=!state.textBold;draw()};$("#italicBtn").onclick=()=>{push();state.textItalic=!state.textItalic;draw()};
$$(".presets button").forEach(b=>b.onclick=()=>{push();state.text=b.dataset.text;$("#textEditor").classList.remove("hidden");$("#textValue").value=state.text;draw()});
$("#clearDecor").onclick=()=>{push();state.decor=[];draw()};$("#saveBtn").onclick=saveGallery;$("#downloadBtn").onclick=()=>$("#downloadModal").classList.add("show");
$$(".download-options button").forEach(b=>b.onclick=()=>download(b.dataset.format));$("#surpriseBtn").onclick=surprise;$("#undoBtn").onclick=undo;$("#redoBtn").onclick=redo;
$("#beforeAfter").onclick=()=>{push();state.filter=state.filter==="Original"?"Warm":"Original";draw();toast(state.filter==="Original"?"Before view":"After view")};
$("#collageBtn").onclick=()=>{push();state.collage=!state.collage;draw();toast(state.collage?"Collage mode on":"Collage mode off")};$("#shortcutsBtn").onclick=()=>$("#helpModal").classList.add("show");
$("#templateSearch").oninput=()=>renderTemplateGrid();
$$(".tool").forEach(b=>b.onclick=()=>{$$(".tool").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".tool-panel").forEach(x=>x.classList.remove("active"));$("#panel-"+b.dataset.tool).classList.add("active")});
const cw=$("#canvasWrap");cw.ondragover=e=>{e.preventDefault();cw.classList.add("drag")};cw.ondragleave=()=>cw.classList.remove("drag");cw.ondrop=e=>{e.preventDefault();cw.classList.remove("drag");[...e.dataTransfer.files].filter(f=>f.type.startsWith("image/")).forEach(loadImage)};
document.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="s"){e.preventDefault();saveGallery()}if(e.key==="Escape")$$(".modal.show").forEach(m=>m.classList.remove("show"))}
}
function showPage(id){$$(".page").forEach(p=>p.classList.remove("active"));$("#"+id).classList.add("active");window.scrollTo(0,0);if(id==="gallery")renderGallery()}
function loadImage(file){const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{push();state.images.push(im);state.image=im;draw();toast("Photo added ✦")};im.src=r.result};r.readAsDataURL(file)}
function snap(){return {...state,image:null,images:state.images.map(i=>i.src),decor:[...state.decor]}}function push(){history.push(JSON.stringify(snap()));if(history.length>30)history.shift();future=[]}
function restore(s){state={...s,images:[],image:null};(s.images||[]).forEach(src=>{let im=new Image();im.onload=()=>{state.images.push(im);state.image=im;draw()};im.src=src});sync();draw()}
function undo(){if(!history.length)return;future.push(JSON.stringify(snap()));restore(JSON.parse(history.pop()));toast("Changes undone")}function redo(){if(!future.length)return;history.push(JSON.stringify(snap()));restore(JSON.parse(future.pop()));toast("Changes redone")}
function canvasBg(ctx){if(state.bg==="transparent"){ctx.clearRect(0,0,720,900);return}if(state.bg==="grid"){ctx.fillStyle="#fffdf9";ctx.fillRect(0,0,720,900);ctx.strokeStyle="#eaded2";for(let x=0;x<720;x+=36){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,900);ctx.stroke()}for(let y=0;y<900;y+=36){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(720,y);ctx.stroke()}return}if(state.bg==="dots"){ctx.fillStyle="#fffdf9";ctx.fillRect(0,0,720,900);ctx.fillStyle="#d9c5b5";for(let x=18;x<720;x+=28)for(let y=18;y<900;y+=28)ctx.fillRect(x,y,2,2);return}ctx.fillStyle=state.bg;ctx.fillRect(0,0,720,900)}
function rr(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,Math.min(r,w/2,h/2))}
function draw(){const c=$("#canvas"),ctx=c.getContext("2d");ctx.clearRect(0,0,720,900);canvasBg(ctx);const t=data.templates.find(x=>x.id===state.template)||data.templates[0];ctx.save();ctx.shadowColor=`rgba(44,33,27,${state.shadow/100})`;ctx.shadowBlur=state.shadow;ctx.shadowOffsetY=8;ctx.fillStyle=t.bg;rr(ctx,state.border,state.border,720-state.border*2,900-state.border*2,state.radius);ctx.fill();ctx.restore();
let imgs=state.images;if(imgs.length){let a={x:state.border+12,y:state.border+12,w:720-(state.border+12)*2,h:900-(state.border+12)*2};if(state.collage&&imgs.length>1){let gap=10,cols=imgs.length<=2?2:2,rows=Math.ceil(imgs.length/cols),cw=(a.w-gap*(cols-1))/cols,ch=(a.h-gap*(rows-1))/rows;imgs.forEach((im,i)=>imageCover(ctx,im,a.x+(i%cols)*(cw+gap),a.y+Math.floor(i/cols)*(ch+gap),cw,ch))}else imageCover(ctx,state.image,a.x+state.posX*2,a.y+state.posY*2,a.w,a.h)}
if(state.text){ctx.save();ctx.fillStyle="#3b2b23";ctx.font=`${state.textItalic?"italic ":""}${state.textBold?"700":"500"} ${state.textSize}px "DM Sans"`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(state.text,360,840);ctx.restore()}state.decor.forEach(d=>{ctx.save();ctx.font=`${d.size}px serif`;ctx.textAlign="center";ctx.fillStyle="#6f4e37";ctx.fillText(d.char,d.x,d.y);ctx.restore()})}
function imageCover(ctx,im,x,y,w,h){ctx.save();rr(ctx,x,y,w,h,state.radius);ctx.clip();let ir=im.width/im.height,ar=w/h,dw,dh;if(state.fit==="fit"){dw=ir>ar?w:h*ir;dh=ir>ar?w/ir:h}else{dw=ir>ar?h*ir:w;dh=ir>ar?h:w/ir}dw*=state.zoom/100;dh*=state.zoom/100;ctx.filter=data.filters[state.filter]||"none";ctx.drawImage(im,x+(w-dw)/2,y+(h-dh)/2,dw,dh);ctx.restore()}
function buildFrameChoices(){const e=$("#frameChoices");data.templates.forEach(t=>{let b=document.createElement("button");b.textContent=t.name;b.onclick=()=>{push();Object.assign(state,{template:t.id,bg:t.bg,border:t.border,radius:t.radius,shadow:t.shadow});sync();draw();toast("Template applied")};e.append(b)})}
function buildFilterChoices(){const e=$("#filterChoices");Object.keys(data.filters).forEach(n=>{let b=document.createElement("button");b.textContent=n;b.onclick=()=>{push();state.filter=n;draw()};e.append(b)})}
function buildBgChoices(){const e=$("#bgChoices");data.backgrounds.forEach(b=>{let x=document.createElement("button");x.textContent=b.name;x.onclick=()=>{push();state.bg=b.value;draw()};e.append(x)})}
function buildStickerChoices(){const e=$("#stickerChoices");data.stickers.forEach(s=>{let b=document.createElement("button");b.textContent=s;b.onclick=()=>{push();state.decor.push({char:s,x:120+Math.random()*480,y:100+Math.random()*650,size:30+Math.random()*25});draw()};e.append(b)})}
function sync(){["border","radius","shadow","posX","posY","zoom","textSize","letterSpacing"].forEach(id=>$("#"+id).value=state[id]);$("#textValue").value=state.text||""}
function buildCategories(){let e=$("#categoryFilters"),cats=["All",...new Set(data.templates.map(t=>t.category))];cats.forEach((c,i)=>{let b=document.createElement("button");b.textContent=c;b.className=i?"":"active";b.onclick=()=>{$$("#categoryFilters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTemplateGrid()};e.append(b)})}
function renderTemplateGrid(){let q=$("#templateSearch").value.toLowerCase(),cat=$(".filters .active")?.textContent||"All",arr=data.templates.filter(t=>(cat==="All"||t.category===cat)&&t.name.toLowerCase().includes(q));$("#templateGrid").innerHTML=arr.map(t=>`<article class="template-card"><div class="template-preview" style="background:${t.bg}"><div style="background:linear-gradient(145deg,#c49b7e,#76513e);padding:${Math.max(8,t.border/2)}px;border-radius:${t.radius}px">Framey</div></div><div class="template-info"><div><b>${t.name}</b><span>${t.category}</span></div><button onclick="applyTemplate('${t.id}')">Use →</button></div></article>`).join("")||'<div class="gallery-empty"><strong>Nothing matched your search.</strong>Try another template.</div>'}
window.applyTemplate=id=>{let t=data.templates.find(x=>x.id===id);push();Object.assign(state,{template:t.id,bg:t.bg,border:t.border,radius:t.radius,shadow:t.shadow});showPage("create");sync();draw();toast("Template applied ✦")}
function surprise(){push();let t=data.templates[Math.floor(Math.random()*data.templates.length)];Object.assign(state,{template:t.id,bg:data.backgrounds[Math.floor(Math.random()*data.backgrounds.length)].value,border:8+Math.floor(Math.random()*35),radius:Math.floor(Math.random()*20),shadow:10+Math.floor(Math.random()*25),filter:Object.keys(data.filters)[Math.floor(Math.random()*Object.keys(data.filters).length)],text:["little moments","summer '26","dear memories","life lately"][Math.floor(Math.random()*4)]});state.decor=[{char:data.stickers[Math.floor(Math.random()*data.stickers.length)],x:120+Math.random()*480,y:100+Math.random()*650,size:40}];sync();draw();toast("A little surprise ✦")}
function saveGallery(){gallery.unshift({id:Date.now(),img:$("#canvas").toDataURL("image/png"),date:new Date().toLocaleDateString(),template:(data.templates.find(t=>t.id===state.template)||{}).name||"Custom"});gallery=gallery.slice(0,30);localStorage.setItem("framey-gallery",JSON.stringify(gallery));renderGallery();toast("Frame saved ✦")}
function renderGallery(){let e=$("#galleryGrid");if(!gallery.length){e.innerHTML='<div class="gallery-empty"><strong>No memories here yet.</strong>Your gallery is waiting for its first memory.<br><br><button class="btn primary" onclick="showPage(\'create\')">Create your first frame</button></div>';return}e.innerHTML=gallery.map(g=>`<article class="gallery-card"><img src="${g.img}" alt="Saved Framey memory"><div class="gallery-info"><div><b>${g.template}</b><small>${g.date}</small></div><div><button onclick="downloadSaved('${g.id}')">Download</button> <button onclick="deleteSaved('${g.id}')">Delete</button></div></div></article>`).join("")}
window.deleteSaved=id=>{gallery=gallery.filter(g=>String(g.id)!==String(id));localStorage.setItem("framey-gallery",JSON.stringify(gallery));renderGallery();toast("Memory deleted")};window.downloadSaved=id=>{let g=gallery.find(x=>String(x.id)===String(id));let a=document.createElement("a");a.href=g.img;a.download=`framey-${g.id}.png`;a.click();toast("Image downloaded")};
function download(fmt){let a=document.createElement("a");a.href=$("#canvas").toDataURL(fmt==="jpeg"?"image/jpeg":"image/png",.92);a.download=`framey-${Date.now()}.${fmt==="jpeg"?"jpg":"png"}`;a.click();$("#downloadModal").classList.remove("show");toast("Image downloaded")}
let timer;function toast(m){let t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>t.classList.remove("show"),1800)}